
# MODEL PARAMETERS
item_dim: 2
hidden_dim: 2
num_users: 1000
maxlen_time: 20
maxlen_slate: 5
num_items: 30
num_groups: 3
softmax_mult: 1.0 # multiply all softmax with this
bias_noclick: 1.0
num_test_users: 200
t_testsplit: 10
device: cpu

# TRAINING PARAMETERS
batch_size: 100
learning_rate: 0.01
patience: 300