
# MODEL PARAMETERS
#name: prior=N(0,0.5) #maxscale=1 #prior=N(0,0.1),
train_seed: 0
real_data: False
item_dim: 2
hidden_dim: 2
num_users: 1000
maxlen_time: 20
maxlen_slate: 4
num_items: 300
num_groups: 30
true_softmax_mult: 2.0 # multiply all softmax with this
softmax_mult: 2.0 # multiply all softmax with this
true_bias_noclick: 1.0
num_test_users: 500
t_testsplit: 10
device: cpu
model_type: ar1
dist: "dot"

### Priors
prior_groupvec_scale: 1.0
prior_groupscale_scale: 1.0
prior_userinit_scale: 1.0
guide_userinit: True
guide_maxscale: 10.0
prior_bias_scale: 5.0
# AR(1) priors
prior_gamma_mean: 0.5
prior_gamma_scale: 20.0
#RNN priors
prior_rnn_scale: 3.0

# TRAINING PARAMETERS
max_epochs : 5000
start_true: False
batch_size: 100
learning_rate: 0.02
patience: 100
calc_footrule: False
# 