
# MODEL PARAMETERS
name: maxscale=1 #prior=N(0,0.1),
item_dim: 2
hidden_dim: 2
num_users: 10000
maxlen_time: 20
maxlen_slate: 4
num_items: 50
num_groups: 5
softmax_mult: 2.0 # multiply all softmax with this
bias_noclick: 1.0
num_test_users: 1000
t_testsplit: 10
device: cpu

# Priors
prior_groupvec_scale: 0.1
prior_groupscale_scale: 0.1
prior_userinit_scale: 0.1
guide_maxscale: 1.0

# TRAINING PARAMETERS
batch_size: 100
learning_rate: 0.05
patience: 60
# 