
# MODEL PARAMETERS
name: ar1
train_seed: 0
real_data: False
item_dim: 2
hidden_dim: 2
num_users: 1000
maxlen_time: 20
maxlen_slate: 5
num_items: 500
num_groups: 50
true_softmax_mult: 5.0 # multiply all softmax with this
true_bias_noclick: 2.0
num_test_users: 100
t_testsplit: 5
device: cpu
model_type: ar1
dist: "l2"

### Priors
prior_scale: 0.01
prior_softmax_mult_scale: 3.0
prior_groupvec_scale: 1.0
prior_groupscale_scale: 1.0
prior_userinit_scale: 1.0
guide_userinit: True
guide_maxscale: 10.0
prior_bias_scale: 5.0
# AR(1) priors
prior_gamma_mean: 0.5
prior_gamma_scale: 5.0
#RNN priors
prior_rnn_scale: 2.0

# TRAINING PARAMETERS
max_epochs : 5000
start_true: False
batch_size: 128
learning_rate: 0.05
patience: 100
calc_footrule: False
# 