
# MODEL PARAMETERS
name: pretrain
train_seed: 1
real_data: True
device: cuda
maxlen_action: 25
maxlen_time: 20
split_trainvalid: 0.95
t_testsplit: 5

# DATA PREPROC PARAMETERS
end_date: 2020-05-17
lookback: 40
lookforward_test: 0
data_type: lake-noclickrate-0.2
data_path: gs://recommendation-exploded/sequences/lake-noclickrate-0.2
data_dir: data_real
min_user_clicks: 10
min_item_views: 400


### MODEL SETTINGS ###
item_dim: 50
hidden_dim: 100
user_model: gru
item_model: pretrained
dist: dot
user_init: False # should initial user state be user dependent or global?

# priors
prior_scale: 1.0 # scales the weight of the prior vs likelihood in optimization
guide_maxscale: 0.001
prior_softmax_mult_scale: 5.0
prior_groupvec_scale: 5.0
prior_groupscale_scale: 0.05
prior_userinit_scale: 0.5
prior_bias_scale: 5.0
# AR(1) priors
prior_gamma_mean: 0.5
prior_gamma_scale: 0.5
#RNN priors
prior_rnn_scale: 2.0

# TRAINING PARAMETERS
max_epochs : 1000
start_true: False
batch_size: 2056
learning_rate: 0.01
patience: 60
calc_footrule: False
stopping_criteria: valid/loss
# 