
# MODEL PARAMETERS
#name: prior=N(0,0.5) #maxscale=1 #prior=N(0,0.1),
real_data: False
item_dim: 2
hidden_dim: 2
num_users: 500
maxlen_time: 20
maxlen_slate: 4
num_items: 50
num_groups: 5
softmax_mult: 2.0 # multiply all softmax with this
bias_noclick: 1.0
num_test_users: 300
t_testsplit: 10
device: cpu
model_type: ar1
# Priors
prior_groupvec_scale: 1.0 #0.1
prior_groupscale_scale: 1.0 #0.1
prior_userinit_scale: 1.0 #0.1
guide_userinit: True
guide_maxscale: 10.0

# TRAINING PARAMETERS
start_true: False
batch_size: 100
learning_rate: 0.05
patience: 60
# 