
# MODEL PARAMETERS
item_dim: 2
hidden_dim: 2
num_users: 5000
batch_user: 50
maxlen_time: 20
maxlen_slate: 3
num_items: 30
num_groups: 3
softmax_mult: 1.0 # multiply all softmax with this
bias_noclick: 1.0
device: cpu

# TRAINING PARAMETERS
batch_size: 100